[OPP] [DRA7] Fix build with OPP_DRA7XX_DEBUG
Fix build error when OPP_DRA7XX_DEBUG is defined.

arch/arm/mach-omap/dra7/opp_dra7xx.c:163:14: error: 'VDD_DRA7XX_WKUP' undeclared (first use in this function)
for (vdd = VDD_DRA7XX_WKUP; vdd < VDD_DRA7XX_ID_MAX; vdd++) {
                 ^~~~~~~~~~~~~~~
arch/arm/mach-omap/dra7/opp_dra7xx.c:163:14: note: each undeclared identifier is reported only once for each function it appears in
arch/arm/mach-omap/dra7/opp_dra7xx.c:170:19: error: 'opp' undeclared (first use in this function)
       i, (void *) &opp);

Acked-by: Praneeth Bajjuri <praneeth@ti.com>
Signed-off-by: Lokesh Vutla <lokeshvutla@ti.com>
Signed-off-by: Nishanth Menon <nm@ti.com>