[LINUX][MEM] Remove inline from global functions
inline with a static variable causes gcc 5.2 to croak and die

Fixes:
linux/linux_mem.h:51:14: warning: inline function ‘lmem_phys2virt’ declared but never defined
 inline void *lmem_phys2virt(void *addr);
              ^
linux/linux_mem.c:239:34: warning: ‘mem_map_base’ is static but used in inline function ‘lmem_phys2virt’ which is not static
  return (void *) ((unsigned int) mem_map_base +
                                  ^
/bin/sh: 1: git: not found
common/mem.o: In function `mem_phys2virt':
mem.c:(.text+0x34): undefined reference to `lmem_phys2virt'
collect2: error: ld returned 1 exit status

Reported-by: Robert C Nelson <robertcnelson@gmail.com>
Signed-off-by: Nishanth Menon <nm@ti.com>